<?php
/**
 * netz98 InfoFiles magento module
 *
 * LICENSE
 *
 * Copyright © 2011.
 * netz98 new media GmbH. Alle Rechte vorbehalten.
 *
 * Die Nutzung und Weiterverbreitung dieser Software in kompilierter oder nichtkompilierter Form, mit oder ohne Veränderung, ist unter den folgenden Bedingungen zulässig:
 *
 * 1. Weiterverbreitete kompilierte oder nichtkompilierte Exemplare müssen das obere Copyright, die Liste der Bedingungen und den folgenden Verzicht im Sourcecode enthalten.
 * 2. Alle Werbematerialien, die sich auf die Eigenschaften oder die Benutzung der Software beziehen, müssen die folgende Bemerkung enthalten: "Dieses Produkt enthält Software, die von der netz98 new media GmbH entwickelt wurde."
 * 3. Der Name der netz98 new media GmbH darf nicht ohne vorherige ausdrückliche, schriftliche Genehmigung zur Kennzeichnung oder Bewerbung von Produkten, die von dieser Software abgeleitet wurden, verwendet werden.
 * 4. Es ist Lizenznehmern der netz98 new media GmbH nur dann erlaubt die veränderte Software zu verbreiten, wenn jene zu den Bedingungen einer Lizenz, die eine Copyleft-Klausel enthält, lizenziert wird.
 *
 * Diese Software wird von der netz98 new media GmbH ohne jegliche spezielle oder implizierte Garantien zur Verfügung gestellt. So übernimmt die netz98 new media GmbH keine Gewährleistung für die Verwendbarkeit der Software für einen speziellen Zweck oder die generelle Nutzbarkeit. Unter keinen Umständen ist netz98 haftbar für indirekte oder direkte Schäden, die aus der Verwendung der Software resultieren. Jegliche Schadensersatzansprüche sind ausgeschlossen.
 *
 *
 * Copyright © 2011
 * netz98 new media GmbH. All rights reserved.
 *
 * The use and redistribution of this software, either compiled or uncompiled, with or without modifications are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of compiled or uncompiled source must contain the above copyright notice, this list of the conditions and the following disclaimer:
 * 2. All advertising materials mentioning features or use of this software must display the following acknowledgement: “This product includes software developed by the netz98 new media GmbH, Mainz.”
 * 3. The name of the netz98 new media GmbH may not be used to endorse or promote products derived from this software without specific prior written permission.
 * 4. License holders of the netz98 new media GmbH are only permitted to redistribute altered software, if this is licensed under conditions that contain a copyleft-clause.
 * This software is provided by the netz98 new media GmbH without any express or implied warranties. netz98 is under no condition liable for the functional capability of this software for a certain purpose or the general usability. netz98 is under no condition liable for any direct or indirect damages resulting from the use of the software. Liability and Claims for damages of any kind are excluded.
 */

/**
 * @see N98_InfoFiles_Block_Adminhtml_Media_Uploader
 */
?>

<?php
/**
 * Uploader-js files already included by magento when using >=1.9.3 or SUPEE-8788 installed
 */
?>
<?php if (!class_exists("Mage_Uploader_Block_Abstract")) { ?>
	<?php echo $this->helper('adminhtml/js')->includeScript('lib/flex.js') ?>
	<?php echo $this->helper('adminhtml/js')->includeScript('mage/adminhtml/flexuploader.js') ?>
	<?php echo $this->helper('adminhtml/js')->includeScript('lib/FABridge.js') ?>
<?php } ?>

<?php echo $this->helper('adminhtml/js')->getTranslatorScript() ?>


<?php if (class_exists("Mage_Uploader_Block_Abstract")) { ?>
	<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
	    <div class="buttons a-right">
	        <?php echo $this->getBrowseButtonHtml(); ?>
	        <?php echo $this->getUploadButtonHtml(); ?>
	    </div>
	</div>
	<div class="no-display" id="<?php echo $this->getElementId('template') ?>">
	    <div id="{{id}}-container" class="file-row">
	        <span class="file-info">{{name}} {{size}}</span>
	        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
	        <span class="progress-text"></span>
	        <div class="clear"></div>
	    </div>
	</div>
	<script type="text/javascript">
	    (function() {
	        var uploader = new Uploader(<?php echo $this->getJsonConfig(); ?>);

			<?php
			/**
			 * for document.on see: https://github.com/Agence-DnD/PIMGento/pull/177/commits/c7f019d7676786abff47d8a641c968268fe98557?diff=split
			 * response only in uploader:fileSuccess included, not in uploader:success
			 * response being generated in FilesController.php
			 */
			?>
			document.on('uploader:fileSuccess', function(event) {

				// has the event been fired from the Infofiles-Container?
				if (event.memo.containerId!='<?php echo $this->getHtmlId() ?>') return;

				var templateElement = $('infofiles_template');
				var template = new Template('<tr id="__id__" class="preview">' +
				    templateElement.innerHTML + '</tr>', new RegExp(
				    '(^|.|\\r|\\n)(__([a-zA-Z0-9_]+)__)', ''))

				var response = event.memo.response.evalJSON();
				// ignore errornous files
				if (response.error) return;
				var listElement = $('infofiles_list');
				var html = template.evaluate(response);
				Element.insert(listElement, {
				    bottom :html
				});
			});

	        if (varienGlobalEvents) {
	            varienGlobalEvents.attachEventHandler('tabChangeBefore', uploader.onContainerHideBefore);
	        }
	    })();
	</script>

<?php } else { ?>

	<div id="<?php echo $this->getHtmlId() ?>" class="uploader">
	    <div class="buttons">
	        <?php /* buttons included in flex object */ ?>
	        <?php  /*echo $this->getBrowseButtonHtml()*/  ?>
	        <?php  /*echo $this->getUploadButtonHtml()*/  ?>
	        <div id="<?php echo $this->getHtmlId() ?>-install-flash" style="display:none">
	            <?php echo Mage::helper('media')->__('This content requires last version of Adobe Flash Player. <a href="%s">Get Flash</a>', 'http://www.adobe.com/go/getflash/') ?>
	        </div>
	    </div>
	    <div class="clear"></div>
	    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template">
	        <div id="{{id}}" class="file-row">
	        <span class="file-info">{{name}} ({{size}})</span>
	        <span class="delete-button"><?php echo $this->getDeleteButtonHtml() ?></span>
	        <span class="progress-text"></span>
	        <div class="clear"></div>
	        </div>
	    </div>
	    <div class="no-display" id="<?php echo $this->getHtmlId() ?>-template-progress">
	        {{percent}}% {{uploaded}} / {{total}}
	    </div>
	</div>

	<script type="text/javascript">
	//<![CDATA[

	var maxUploadFileSizeInBytes = <?php echo $this->getDataMaxSizeInBytes() ?>;
	var maxUploadFileSize = '<?php echo $this->getDataMaxSize() ?>';

	<?php echo $this->getJsObjectName() ?> = new Flex.Uploader('<?php echo $this->getHtmlId() ?>', '<?php echo $this->getUploaderUrl('media/uploader.swf') ?>', <?php echo $this->getConfigJson() ?>);
	<?php echo $this->getJsObjectName() ?>.onFilesComplete = function(completedFiles){
	    // remove uploaded files from the list
	    completedFiles.each(function(file){
	        var templateElement = $('infofiles_template');
	        var template = new Template('<tr id="__id__" class="preview">' +
	            templateElement.innerHTML + '</tr>', new RegExp(
	            '(^|.|\\r|\\n)(__([a-zA-Z0-9_]+)__)', ''))

	        var response = file.response.evalJSON();
	        // ignore errornous files
	        if (response.error) return;
	        var listElement = $('infofiles_list');
	        var html = template.evaluate(response);
	        Element.insert(listElement, {
	            bottom :html
	        });
	        <?php echo $this->getJsObjectName() ?>.removeFile(file.id);
	    });
	}
	// hide flash buttons
	if ($('<?php echo $this->getHtmlId() ?>-flash') != undefined) {
	    $('<?php echo $this->getHtmlId() ?>-flash').setStyle({float:'left'});
	}
	//]]>

	if (varienGlobalEvents) {
	    varienGlobalEvents.attachEventHandler('tabChangeBefore', <?php echo $this->getJsObjectName() ?>.onContainerHideBefore);
	}

	//]]>
	</script>
<?php } ?>
