<?php
/**
 * netz98 InfoFiles magento module
 *
 * LICENSE
 *
 * Copyright © 2011.
 * netz98 new media GmbH. Alle Rechte vorbehalten.
 *
 * Die Nutzung und Weiterverbreitung dieser Software in kompilierter oder nichtkompilierter Form, mit oder ohne Veränderung, ist unter den folgenden Bedingungen zulässig:
 *
 * 1. Weiterverbreitete kompilierte oder nichtkompilierte Exemplare müssen das obere Copyright, die Liste der Bedingungen und den folgenden Verzicht im Sourcecode enthalten.
 * 2. Alle Werbematerialien, die sich auf die Eigenschaften oder die Benutzung der Software beziehen, müssen die folgende Bemerkung enthalten: "Dieses Produkt enthält Software, die von der netz98 new media GmbH entwickelt wurde."
 * 3. Der Name der netz98 new media GmbH darf nicht ohne vorherige ausdrückliche, schriftliche Genehmigung zur Kennzeichnung oder Bewerbung von Produkten, die von dieser Software abgeleitet wurden, verwendet werden.
 * 4. Es ist Lizenznehmern der netz98 new media GmbH nur dann erlaubt die veränderte Software zu verbreiten, wenn jene zu den Bedingungen einer Lizenz, die eine Copyleft-Klausel enthält, lizenziert wird.
 *
 * Diese Software wird von der netz98 new media GmbH ohne jegliche spezielle oder implizierte Garantien zur Verfügung gestellt. So übernimmt die netz98 new media GmbH keine Gewährleistung für die Verwendbarkeit der Software für einen speziellen Zweck oder die generelle Nutzbarkeit. Unter keinen Umständen ist netz98 haftbar für indirekte oder direkte Schäden, die aus der Verwendung der Software resultieren. Jegliche Schadensersatzansprüche sind ausgeschlossen.
 *
 *
 * Copyright © 2011
 * netz98 new media GmbH. All rights reserved.
 *
 * The use and redistribution of this software, either compiled or uncompiled, with or without modifications are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of compiled or uncompiled source must contain the above copyright notice, this list of the conditions and the following disclaimer:
 * 2. All advertising materials mentioning features or use of this software must display the following acknowledgement: “This product includes software developed by the netz98 new media GmbH, Mainz.”
 * 3. The name of the netz98 new media GmbH may not be used to endorse or promote products derived from this software without specific prior written permission.
 * 4. License holders of the netz98 new media GmbH are only permitted to redistribute altered software, if this is licensed under conditions that contain a copyleft-clause.
 * This software is provided by the netz98 new media GmbH without any express or implied warranties. netz98 is under no condition liable for the functional capability of this software for a certain purpose or the general usability. netz98 is under no condition liable for any direct or indirect damages resulting from the use of the software. Liability and Claims for damages of any kind are excluded.
 */
/**
 * Tab for uploading and managing files
 */

$files = $this->getFileCollection();
$store = $this->getProduct()->getStore();

?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Files') ?></h4>
    </div>

    <div id="group_files" class="fieldset fieldset-wide">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <?php if ($store->getId() == 0): ?>
                        <?php echo $this->__('Files you upload in this view will be visible in all store views.'); ?>
                        <?php else: ?>
                        <?php
                            $storeName = $store->getName();
                            echo $this->__('Files you upload in this view are only visible in "%s".',$storeName);
                        ?>
                        <?php endif; ?>
                    </li>
                </ul>
            </li>
        </ul>
        <div class="grid">
            <table class="data border" id="files_content_grid" cellspacing="0" width="100%">
                <colgroup>
                    <col width="150">
                    <col>
                    <col width="70">
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th><?php echo $this->__("File") ?></th>
                        <th><?php echo $this->__("Label") ?></th>
                        <th class="last"><?php echo $this->__("Remove") ?></th>
                    </tr>
                </thead>
                <tbody id="infofiles_list">
<?php foreach ($files as $file): ?>
                        <tr id="infofile<?php echo $file->getId() ?>">
                            <td class="cell-file"><a href="<?php echo $file->getUrl() ?>" target="_blank"><?php echo $file->getName() ?></a></td>
                        <td class="cell-label"><input class="input-text" type="text" name="infofile_existing_label[<?php echo $file->getId() ?>]" value="<?php echo htmlspecialchars($file->getLabel()) ?>"></td>
                        <td class="cell-remove a-center last"><input type="checkbox" name="infofile_existing_remove[<?php echo $file->getId() ?>]"></td>
                    </tr>
<?php endforeach; ?>
                    <tr id="infofiles_template" class="template no-display">
                        <td class="cell-file"><input type="hidden" name="infofile_file[]" value="__file__"><input type="hidden" name="infofile_name[]" value="__name__"><a href="__url__" target="_blank">__name__</a></td>
                        <td class="cell-label"><input class="input-text" type="text" name="infofile_label[]"></td>
                        <td class="cell-remove a-center last">&nbsp;</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="100" class="last" style="padding:8px">
<?php
                            echo $this->getLayout()->createBlock('n98infofiles/adminhtml_media_uploader')->toHtml();
?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>