<?php
/**
 * Custom tab template
 */
?>

<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Files') ?></h4>
    </div>

    <div id="group_files" class="fieldset fieldset-wide">

        <div class="grid">
            <table class="data border" id="files_content_grid" cellspacing="0" width="100%">
                <colgroup>
                    <col width="150">
                    <col>
                    <col width="70">
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th><?php echo $this->__("File") ?></th>
                        <th><?php echo $this->__("Description") ?></th>
                        <th class="last"><?php echo $this->__("Remove") ?></th>
                    </tr>
                </thead>
                <tbody id="media_gallery_content_list">
                    <tr id="media_gallery_content_template" class="template no-display">
                            <td class="cell-image">foo</td>
                            <td class="cell-label"><input class="input-text"  type="text"></td>
                            <td class="cell-remove a-center last"><input type="checkbox"></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="100" class="last" style="padding:8px">
<?php
    echo $this->getLayout()->createBlock('n98infofiles/adminhtml_media_uploader')->toHtml();
?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>



        <div class="input-field">
         <label for="custom_field">Custom Field</label>
         <input type="text" class="input-text" name="custom_field" id="custom_field" />
        </div>


    </div>
</div>
