<?php
/**
 * Custom tab template
 */
?>

<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Files') ?></h4>
    </div>

    <div id="group_files" class="fieldset fieldset-wide">

        <div class="grid">
            <table class="data border" id="files_content_grid" cellspacing="0" width="100%">
                <colgroup>
                    <col width="150">
                    <col>
                    <col width="70">
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th><?php echo $this->__("File") ?></th>
                        <th><?php echo $this->__("Description") ?></th>
                        <th class="last"><?php echo $this->__("Remove") ?></th>
                    </tr>
                </thead>
                <tbody id="infofiles_list">
                    <tr id="infofiles_template" class="template no-display">
                            <td class="cell-file"><input type="hidden" name="infofile_file[]" value="__file__"><input type="hidden" name="infofile_name[]" value="__name__"><a href="__url__">__name__</a></td>
                            <td class="cell-label"><input class="input-text" type="text" name="infofile_label[]"></td>
                            <td class="cell-remove a-center last"><input type="checkbox" name="infofile_remove[]"></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="100" class="last" style="padding:8px">
<?php
    echo $this->getLayout()->createBlock('n98infofiles/adminhtml_media_uploader')->toHtml();
?>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>



        <div class="input-field">
         <label for="custom_field">Custom Field</label>
         <input type="text" class="input-text" name="custom_field" id="custom_field" />
        </div>


    </div>
</div>
